# Generated by Django 6.0.2 on 2026-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
