# Generated by Django 6.0.4 on 2026-04-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_candidate_education'),
        ('voting', '0009_voteauditlog_enhanced'),
    ]

    operations = [
    ]
