# Generated by Django 6.0.2 on 2026-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_merge_20260419_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteauditlog',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='voteauditlog',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='voteauditlog',
            name='ip_vote_count',
        ),
        migrations.RemoveField(
            model_name='voteauditlog',
            name='is_weekend',
        ),
        migrations.RemoveField(
            model_name='voteauditlog',
            name='session_age',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography / candidate statement', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, help_text='Key policy points, one per line', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.CharField(blank=True, help_text='Campaign slogan shown as pull-quote', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='hour_of_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='otp_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='voteauditlog',
            name='time_since_otp_request',
            field=models.FloatField(default=0.0),
        ),
    ]
