# Generated by Django 6.0.2 on 2026-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_remove_voteauditlog_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteauditlog',
            name='device_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
